name: CI-Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # pull_request는 main 브랜치에 대한 pr이 생성되었을 때 실행됨.
  # ex) develop 브랜치에서 push를 하고 main 브랜치에 대한 pr을 생성했을 때 실행
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "context"
        env:
          COMMIT_ID: ${{ github.sha }}
        run: echo "Commit id => $COMMIT_ID"
      - name: print nickname
        env:
          TEST_NAME: ${{ secrets.TEST_NICKNAME }}
        run: echo my Token is $TEST_NAME
      - name: print nickname
        env:
          TEST_NAME: ${{ secrets.TEST_NICKNAME }}
        run: echo my Token is $TEST_NAME
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
