name: CI-Test

on:
  push:
    branches: ["main"]
  #pull_request:
  # branches: ["develop"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run pwd
        run: pwd
      - name: Run ls -al
        run: ls -al
      - name: Check Node V
        run: node -v
      - name: "context"
        env:
          COMMIT_ID: ${{ github.sha }}
        run: echo "Commit id => $COMMIT_ID"

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
